// Copyright 2019-2024 Tauri Programme within The Commons Conservancy
// SPDX-License-Identifier: Apache-2.0
// SPDX-License-Identifier: MIT

// This is a standalone Gradle project (not generated by `cargo tauri android
// init`). It exists to regression-test one thing: that
// `crates/tauri/mobile/android/consumer-rules.pro`, applied exactly as a real
// consuming app would receive it (via `implementation(project(":tauri-android"))`
// -> consumerProguardFiles), is sufficient on its own to keep reflective Tauri
// plugin discovery working after R8 minification. See app/README.md.

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "android-r8-plugin-discovery"

include(":app")

// Reference the real library sources directly -- the same thing
// crates/tauri-build/src/mobile.rs does for real Tauri apps (it writes
// `project(':tauri-android').projectDir = new File(<DEP_TAURI_ANDROID_LIBRARY_PATH>)`
// into the generated tauri.settings.gradle). Pointing at a copy or a stub here
// would defeat the purpose of the test.
include(":tauri-android")
project(":tauri-android").projectDir = file("../../crates/tauri/mobile/android")
